import './globals.css'
import { Inter } from 'next/font/google'
import Head from './Head.js';

const inter = Inter({ subsets: ['latin'] })


// export const metadata = {
//   title: 'Space Site',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head name={"Space Site"}/>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
